const RESERVED_USERNAME_LIST = [
  'admin',
  'api',
  'app',
  'auth',
  'www',
  'support',
  'help',
  'about',
  'terms',
  'privacy',
  'login',
  'signup',
  'dashboard',
  'akun',
  'settings',
  'checkout',
  'nagihin',
  'masuk',
  'daftar',
  'lupa-password',
  'reset-password',
  'callback',
  'lengkapi-profil',
  'pesanan',
  'produk',
  'pricing',
  'harga',
  'docs',
  'health',
  '_next',
  'favicon.ico',
] as const;

export const RESERVED_USERNAMES: ReadonlySet<string> = new Set(RESERVED_USERNAME_LIST);
